### ISSUE TITLE
oxidization analysis

### ISSUE THREAD

**Issue by SidneyDouw** [SidneyDouw/gitoxide#5]
## built
[GitHub](https://github.com/lukaslueg/built)

### Env vars to set
- `GIT_VERSION: Option<&str>`
- `GIT_DIRTY: Option<bool>`
- `GIT_COMMIT_HASH: Option<&str>`
- `GIT_COMMIT_HASH_SHORT: Option<&str>`
- `GIT_HEAD_REF: Option<&str>` i.e. `Some("refs/heads/master")`

### API
**Main**
- [x] `git2::Repository::discover`
- [x] git-describe / `git2::repo::Repository::describe` with `git2::DescribeOptions` for configuration to find the current tag or the current short id 
- [ ] `git2::repo::Repository::statuses` to find if there are untracked files (dirty)
- [x] `git2::repo::Repository::head` to get the HEAD ref
- [x] `git2::reference::Reference::name` to get the ref name (or branch name?)
- [x] `git2::reference::Reference::peel_to_commit` to get the commit id

**Tests**
- [x] `git2::repo::Repository::init_opts` to initialize a repository
- [x] `git2::repo::Repository::index` - get repos' index file
- [ ] `git2::index::Index::add_path` to update the index with a file
- [ ] `git2::repo::Repository::commit` to add a commit from the updated index
- [x] `git2::repo::Repository::tag` to tag a commit
- [ ] `git2::repo::Repository::set_head_detached`

---

## rustsec
#TODO

---

## shadow-rs
[GitHub](https://github.com/baoyachi/shadow-rs)

### Env vars to set
- `GIT_CLEAN: bool`
- `GIT_STATUS_FILE: String`
- `BRANCH: String`
- `TAG: String`
- `COMMIT_HASH: String`
- `SHORT_COMMIT: String`
- `COMMIT_DATE: String`
- `COMMIT_DATE_2822: String`
- `COMMIT_DATE_3339: String`
- `COMMIT_EMAIL: String`
- `COMMIT_AUTHOR: String`

### API
- [ ] `git2::repo::Repository::statuses` to check if git status is 'clean' (no dirty or staged files) and to get a list of dirty and staged files (if the `git2` feature flag is active)
- [x] discover repo
- [x] get head
- [x] get branch
- [x] get tag
- [x] get commit id
- [x] get commit short id
- [x] commit info(date, author)

---

## cargo-tarpaulin
[GitHub](https://github.com/xd009642/tarpaulin)

git2 could already be replaced entirely by `gitoxide`

### Struct to fill
- comes from [coveralls-api](https://github.com/xd009642/coveralls-api) crate
```rust
pub struct GitInfo {
	pub head: Head,
	pub branch: String,
	pub remotes: Vec<Remote>,
}

pub struct Head {
	pub id: String,
	pub author_name: String,
	pub author_email: String,
	pub committer_name: String,
	pub committer_email: String,
	pub message: String,
}

pub struct Remote {
	pub name: String,
	pub url: String,
}
```

### API
- [x] `git2::Repository::discover`
- [x] `git2::repo::Repository::head` to get the HEAD ref
- [x] get the head branch name
- [x] get head of commit id
- [x] commit details (id, author, committer, message)

---

## tokei
[GitHub](https://github.com/XAMPPRocky/tokei)

### API
**Main**
- Looks like they built a .gitignore matching implementation from scratch. Seems a little too much to replace with functionality from gitoxide.

**Tests**
- [x] git2::Repository::init

---

## bat
[GitHub](https://github.com/sharkdp/bat)

### API
**Main**
- [x] `git2::repo::Repository::discover`
- [ ] `git2::repo::Repository::diff_index_to_workdir`

**Tests**
- [x] `git2::repo::Repository::init` - initialize repository
- [ ] `git2::repo::Repository::index` - get repos' index file
- [ ] `git2::index::Index::add_path` - update index with files
- [ ] `git2::index::Index::write_tree` - write index to tree
- [ ] `git2::repo::Repository::commit` - commit updated index
- [ ] `git2::repo::Repository::checkout_head` - checkout

---

## exa
[GitHub](https://github.com/ogham/exa)

### API
**Main**
- [ ] `git2::repo::Repository::statuses` to find all files and their status
- [x] `git2::Repository::discover`

## broot
[GitHub](https://github.com/Canop/broot)

### API
**Main**
- [x] `git2::repo::Repository::discover // open`
- [ ] `git2::repo::Repository::status_file` - get git status of a single file
- [ ] `git2::repo::Repository::statuses`
- [ ] `git2::repo::Repository::workdir` - get workdir path
- [ ] `git2::repo::Repository::diff_index_to_workdir`
- [x] `git2::Config` - get config entries
- [x] get branch name

**Comment by Byron** [comment]
### Session Notes

- let's put these into oxidization tickets
- `status` like features are part of my grant proposition, and I could do that first so you are unblocked.
- `git push` would be desirable for `jj`
- there is great value of writing all index data back (and to write V4 so we don't have to downgrade index versions, ever), but that's only required if an application wants to mutate the index, like with adding files.
     - How to put it into an application without requiring pathspec matching? It's quite some work for sure.
     - Benefit: you know `index` really well and it's a nice workflow to implement serialization.

### Narratives

- starship completion with `git status` oxidization, while waiting, oxidize some of the ones listed here, close the loop explaining how much faster it's going to be once fully oxidized.

**Comment by Byron** [comment]
Success Stories, we could have more and show them in the README

* https://github.com/stacked-git/stgit/discussions/255

Maybe you can collect more stories and create a section to help people trust using gitoxide more.

Also, see why one would use it over `git2`

- opens every repository on earth
    - handles workspaces correctly as well as sparse repositories
- compiles just as fast as `git2` and has room for optimization
- performance way better
- typical Rust vs C benefits

**Comment by Byron** [comment]
I have decided to start collecting interesting articles about `gitoxide` [in a new column of the project dashboard](https://github.com/Byron/gitoxide/projects/1#column-19293340) for now, along with summaries of the best bits.
